config/routes.rb
Rails.application.routes.draw do

  resources :recipes
  devise_for :users
  resources :categories

  resources :ingredients
  resources :users

  get 'search_by_categories' => 'home#search_by_categories', as: :search_by_categories
  get 'search_by_users' => 'home#search_by_users', as: :search_by_users

  root :to => "home#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/recipe.rb
class Recipe < ApplicationRecord
	has_and_belongs_to_many :categories, dependent: :destroy
	
	has_many :recipe_items, dependent: :destroy, inverse_of: :recipe
	accepts_nested_attributes_for :recipe_items, :allow_destroy => true

	belongs_to :user

	validates :title, presence: true, length: { minimum: 3, unless: "title.blank?" }
	validates :directions, presence: true, length: { minimum: 15, unless: "directions.blank?" }
	validates :servings, numericality: { greater_than_or_equal_to: 1, unless: "servings.blank?" }
	validates :categories, presence: true
	validates :recipe_items, presence: true
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]
  before_action :set_form_options, only: [:new, :create, :edit, :update]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update]

  before_filter :require_permission, only: :edit

  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.where(user_id: current_user.id)
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
    recipe_item = @recipe.recipe_items.build
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
      format.html { redirect_to @recipe, notice: 'Receita salva com sucesso!' }
      format.json { render :show, status: :created, location: @recipe }
      else
      format.html { render :new }
      format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
      format.html { redirect_to @recipe, notice: 'Receita salva com sucesso!' }
      format.json { render :show, status: :ok, location: @recipe }
      else
      format.html { render :edit }
      format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Receita excluida com sucesso!' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def recipe_params
    params.require(:recipe).permit(
      :title, :preparation_time, :servings, :directions, :user_id, {:category_ids => []}, 
      recipe_items_attributes: [:id, :ingredient_id, :amount, :measurement_unit_id, :_destroy]
    )
  end

  def require_permission
    if current_user != Recipe.find(params[:id]).user
      redirect_to root_path
    end
  end

  def set_form_options
    @categories = Category.where(user_id: current_user.id)
    @ingredients = Ingredient.where(user_id: current_user.id)
    @measurement_units = MeasurementUnit.all()
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
	def show_recipe_item_full_name(recipe_item)
		full_name = recipe_item.amount.floor.to_s
		if recipe_item.measurement_unit.name.length > 2
			full_name +=  " " + recipe_item.measurement_unit.name.pluralize + " de "
		else
			full_name += recipe_item.measurement_unit.name + " "
		end

		full_name + recipe_item.ingredient.name
  end
end

app/views/recipes/_form.html.erb
<%= form_for(recipe) do |f| %>
  <% if recipe.errors.any? %>
    <div id="error_explanation">
      <ul class="error_messages">
        <% recipe.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :user_id, value: current_user.id %>

  <div class="col s12 card card-large">
    <div class="row">
      <div class="input-field col s12">
        <%= f.text_field :title,  id: 'title' %>
        <label for="title">Título</label>
      </div>

      <div class="input-field col s12 m4">
        <%= f.text_field :preparation_time,  id: 'preparation_time', value: show_time_only(recipe.preparation_time), class: 'timepicker' %>
        <label for="preparation_time">Tempo de Preparo</label>
      </div>

      <div class="input-field col s12 m4">
        <%= f.number_field :servings,  id: 'servings' %>
        <label for="servings">Porções</label>
      </div>

      <div class="input-field col s12 m4">
        <%= f.select :category_ids, @categories.map{ |c| [c.name, c.id] }.unshift(["Escolha uma opção", "0"]), { disabled: '0' }, { multiple: true, id: 'category_ids' } %>
        <label for="category_ids">Categorias</label>
      </div>

      <div class="col s12" id="ingredients">
        <%= f.fields_for :recipe_items do |builder| %>
          <%= render "recipe_item_fields", f: builder %>
        <% end %>

        <div class="input-field col s12">
          <%= link_to_add_fields f, :recipe_items %>
        </div>
      </div>

      <div class="input-field col s12">
        <%= f.text_area :directions, id: 'directions', class: 'materialize-textarea' %>
        <label for="directions">Modo de Preparo</label>
      </div>
    </div>

    <div class="card-action">
      <%= link_to 'Voltar', recipes_path %>
      <% if !@recipe.new_record? %>
        <%= link_to 'Excluir', recipe, class: 'danger-btn', method: :delete, data: { confirm: 'Tem certeza?' } %>
      <% end %>
      <%= f.submit 'Salvar', class: 'right sucess-btn' %>

    </div>
  </div>

<% end %>

app/views/recipes/_recipe_item_fields.erb
<div class="ingredients-attr">
  <div class="input-field col s6 m6">
    <%= f.select :ingredient_id, @ingredients.map{ |c| [c.name, c.id] }, prompt: 'Escolha uma opção', label: false, id: 'ingredient_id' %>
    <label for="ingredient_id">Ingrediente</label>
  </div>

  <div class="input-field col s2 m2">
    <%= f.number_field :amount,  id: 'amount' %>
    <label for="amount">Quantidade</label>
  </div>

  <div class="input-field col s3 m3">
    <%= f.select :measurement_unit_id, @measurement_units.map{ |c| [c.name, c.id] }, prompt: 'Escolha uma opção', label: false, id: 'measurement_unit_id' %>
    <label for="measurement_unit_id">Unidade</label>
  </div>

  <div class="input-field col s1">
    <%= f.hidden_field :_destroy %>
    <%= link_to '<i class="material-icons">remove</i>'.html_safe, '#', class: "waves-effect waves-light btn btn-remove" %>
  </div>
</div>

app/views/recipes/edit.html.erb
<div class="container">
  <div class="row recipe">
  <h2 class="s12 page-title">Editar Receita</h2>

  <div class="notice-container">
    <p id="notice"><%= notice %></p>
  </div>
  <%= render 'form', recipe: @recipe %>

  </div>
</div>

app/views/recipes/index.html.erb
<div class="container">
  <div class="row recipes">
  <h1 class="s12 page-title">Receitas</h1>

  <div class="notice-container">
    <p id="notice"><%= notice %></p>
  </div>

  <div class="s12 card card-large">
    <table id="table-user">
    <thead>
      <tr>
        <th>Título</th>
        <th>Tempo de Preparo</th>
        <th>Porções</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @recipes.each do |recipe| %>
      <tr>
        <td><%= recipe.title %></td>
        <td><%= show_time_only(recipe.preparation_time) %></td>
        <td><%= recipe.servings %></td>
        <td class="taction"><%= link_to 'Visualizar', recipe_path(recipe), class: 'btn-action primary-btn'  %></td>
        <td class="taction"><%= link_to 'Editar', edit_recipe_path(recipe), class: 'btn-action primary-btn'  %></td>
        <td class="taction"><%= link_to 'Excluir', recipe, class: 'btn-action danger-btn', method: :delete, data: { confirm: 'Tem certeza?' } %></td>
      </tr>
      <% end %>
    </tbody>

    </table>
    <div class="card-action right-align">
    <%= link_to 'Nova Receita', new_recipe_path, class: 'primary-btn' %>
    </div>

  </div>
  </div>
</div>

app/views/recipes/new.html.erb
<div class="container">
  <div class="row recipe">
  <h2 class="s12 page-title">Nova Receita</h2>

  <div class="notice-container">
    <p id="notice"><%= notice %></p>
  </div>
  <%= render 'form', recipe: @recipe %>

  </div>
</div>

app/views/recipes/show.html.erb
<div class="container">
  <div class="row ingredient">
  <!-- <h1 class="s12 page-title">Receita</h1> -->

  <div class="notice-container">
    <p id="notice"><%= notice %></p>
  </div>

  <div class="col s12 card card-medium card-book">
    <div class="row">
      <div class="recipe-title col s12 m8">
        <h2><%= @recipe.title %></h2>
      </div>
      <div class="col s6 m2 recipe-info">
        <i class="material-icons">timer</i>
        <p class="label">preparo</p>
        <p class="info"><%= show_time_only(@recipe.preparation_time) %></p>
      </div>
      <div class="col s6 m2 recipe-info">
        <i class="material-icons">room_service</i>
        <p class="label">porções</p>
        <p class="info"><%= @recipe.servings %></p>
      </div>
    </div>
    <div class="row">
      <div class="col s12 recipe-ingredients">
        <h5 class="subtitle">Ingredientes</h5>
        <ul class="ingredients-list">
          <% @recipe.recipe_items.each do |recipe_item| %>
            <li class="ingredient"><%= show_recipe_item_full_name(recipe_item) %></li>
          <% end %>         
        </ul>
      </div>
      <div class="col s12 recipe-directions">
        <h5 class="subtitle">Modo de Preparo</h5>
        <p><%= @recipe.directions %></p>
      </div>
    </div>
  </div>
  </div>
</div>