config/routes.rb
Rails.application.routes.draw do

  resources :recipes
  devise_for :users
  resources :categories

  resources :ingredients
  resources :users

  get 'search_by_categories' => 'home#search_by_categories', as: :search_by_categories
  get 'search_by_users' => 'home#search_by_users', as: :search_by_users

  root :to => "home#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
	include Gravtastic

	gravtastic
	devise :database_authenticatable, :registerable,
		:recoverable, :rememberable, :trackable, :validatable

	after_create :set_username

	has_many :ingredients
	has_many :categories
	has_many :recipes

	attr_accessor :login

	enum state: [
		:AC, :AL, :AP, :AM, :BA, :CE, :DF, :ES, :GO, :MA, :MT, :MS, :MG, :PA,
		:PB, :PR, :PE, :PI, :RJ, :RN, :RS, :RO, :RR, :SC, :SP, :SE, :TO
	]

	validates :name, presence: true, length: { minimum: 3, unless: "name.blank?" }
	validates :email, presence: true, uniqueness: true
	validates :username, format: { with: /^[a-zA-Z0-9_\.]*$/, multiline: true }

  def set_username
  self.username = self.email.split("@").first
  temp_users = User.where(username: self.username)

  if (temp_users.size > 0)
    self.username = self.username + temp_users.size.to_s
  end

  self.save
  end

  def self.find_for_database_authentication(warden_conditions)
	  conditions = warden_conditions.dup
	  if login = conditions.delete(:login)
	  where(conditions.to_h).where(["username = :value OR email = :value", { :value => login }]).first
	  elsif conditions.has_key?(:username) || conditions.has_key?(:email)
	  where(conditions.to_h).first
	  end
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :destroy]
  before_action :set_edit_user, only: [:edit, :update]
  before_action :authenticate_user!, only: [:edit, :update, :index, :new, :destroy]

  # GET /users/1
  def show
    @recipes = Recipe.where(user_id: params[:id])
  end

  # GET /users/1/edit
  def edit
  end

  # PATCH/PUT /users/1
  def update
  respond_to do |format|
    if @user.update(user_params)
    format.html { redirect_to @user, notice: 'Usuário salvo com sucesso!' }
    format.json { render :show, status: :ok, location: @user }
    else
    format.html { render :edit }
    format.json { render json: @user.errors, status: :unprocessable_entity }
    end
  end
  end

  # DELETE /users/1
  def destroy
  @user.destroy
  respond_to do |format|
    format.html { redirect_to users_url, notice: 'Usuário excluido com sucesso!' }
    format.json { head :no_content }
  end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:name, :email, :state)
  end

  def set_edit_user
    @user = User.find(current_user.id)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <ul class="error_messages">
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="s12 card card-large">
    <div class="row">
      <div class="input-field col s12">
        <i class="material-icons prefix">account_circle</i>
        <%= f.text_field :name,  id: 'name' %>
        <label for="name">Nome</label>
      </div>

      <div class="input-field col s12">
        <i class="material-icons prefix">email</i>
        <%= f.text_field :email, id: 'email' %>
        <label for="email">E-mail</label>
      </div>

      <div class="input-field col s12">
        <i class="material-icons prefix">map</i>
        <%= f.select :state, User.states.keys, prompt: 'Escolha uma opção', label: false, id: 'state' %>
      </div>
    </div>

    <div class="card-action">
      <%= link_to 'Voltar', user  %>
      <%= f.submit 'Salvar', class: 'right sucess-btn' %>
    </div>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="container">
  <div class="row user">
  <h2 class="s12 page-title">Editar Usuário</h2>

  <div class="notice-container">
    <p id="notice"><%= notice %></p>
  </div>
  <%= render 'form', user: @user %>
  
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row user">
  <h1 class="s12 page-title">Usuários</h1>

  <div class="notice-container">
    <p id="notice"><%= notice %></p>
  </div>

  <div class="s12 card card-large">
    <table id="table-user">
    <thead>
      <tr>
      <th>Nome</th>
      <th>Email</th>
      <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td class="taction"><%= link_to 'Perfil', user, class: 'btn-action primary-btn' %></td>
        <td class="taction"><%= link_to 'Editar', edit_user_path(user), class: 'btn-action primary-btn' %></td>
        <td class="taction"><%= link_to 'Excluir', user_path(user), class: 'btn-action danger-btn', method: :delete, data: { confirm: 'Tem certeza?' } %></td>
      </tr>
      <% end %>
    </tbody>
    </table>
    <div class="card-action right-align">
    <%= link_to 'Novo Usuário', new_user_path, class: 'primary-btn' %>
    </div>

  </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="container">
  <div class="row user">
  <h2 class="s12 page-title">Novo Usuário</h2>
    <%= render 'form', user: @user %>
  </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row user">
  <p class="user-recipe-title">Receitas de</p>
  <h1 class="s12 page-title"><%= @user.name %> <% if current_user.present? && @user.id == current_user.id %>
    <%= link_to 'Editar', edit_user_path(@user), class: 'primary-btn edit-link' %>
  <% end %></h1>

  <div class="notice-container">
    <p id="notice"><%= notice %></p>
  </div>
  <div class="row">
    <% @recipes.each do |recipe| %>
    <div class="col s12 m6">
      <div class="card card-medium">
        <div class="card-title">
          <p class="title-name"><%= recipe.title %></p>
          <div class="row">
            <p class="title-subtitle col s6">por <%= recipe.user.name %></p>
            <p class="title-category col s6"><%= recipe.categories.collect { |c| c.name }.join(', ') %></p>
          </div>
        </div>

      <div class="card-action">
        <%= link_to 'VER RECEITA COMPLETA', recipe_path(recipe)  %>
      </div>
      </div>
    </div>
    <% end %>
  </div>

  </div>
</div>