config/routes.rb
Rails.application.routes.draw do

  resources :recipes
  devise_for :users
  resources :categories

  resources :ingredients
  resources :users

  get 'search_by_categories' => 'home#search_by_categories', as: :search_by_categories
  get 'search_by_users' => 'home#search_by_users', as: :search_by_users

  root :to => "home#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
	has_and_belongs_to_many :recipes

  belongs_to :user

  validates :name, presence: true, length: { minimum: 3, unless: "name.blank?" },
		uniqueness: { scope: :user }

	validates :user, presence: true

  before_save :set_normalized_name

  def set_normalized_name
  	self.normalized_name = self.name.parameterize
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  before_filter :require_permission, only: :edit

  # GET /categories
  # GET /categories.json
  def index
  @categories = Category.where(user_id: current_user.id)
  end

  # GET /categories/new
  def new
  @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
  @category = Category.new(category_params)

  respond_to do |format|
    if @category.save
    format.html { redirect_to action: "index", notice: 'Categoria salva com sucesso!' }
    else
    format.html { render :new }
    format.json { render json: @category.errors, status: :unprocessable_entity }
    end
  end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
  respond_to do |format|
    if @category.update(category_params)
    format.html { redirect_to action: "index", notice: 'Categoria salva com sucesso!' }
    else
    format.html { render :edit }
    format.json { render json: @category.errors, status: :unprocessable_entity }
    end
  end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
  @category.destroy
  respond_to do |format|
    format.html { redirect_to categories_url, notice: 'Categoria excluida com sucesso.' }
    format.json { head :no_content }
  end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end
  # Never trust parameters from the scary internet, only allow the white list through.
  def category_params
    params.require(:category).permit(:name, :user_id)
  end

  def require_permission
    teste =
    if current_user != Category.find(params[:id]).user
      redirect_to root_path
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(category) do |f| %>

  <% if category.errors.any? %>
  <div id="error_explanation">
    <ul class="error_messages">
    <% category.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <div class="col s12 m8 offset-m2 card card-large">

  <div class="row">
    <%= f.hidden_field :user_id, value: current_user.id %>
    
    <div class="input-field col s12">
    <%= f.text_field :name,  id: 'name' %>
    <label for="name">Nome</label>
    </div>
  </div>

  <div class="card-action">
    <%= link_to 'Voltar', categories_path %>
    <% if !@category.new_record? %>
    <%= link_to 'Excluir', category, class: 'danger-btn', method: :delete, data: { confirm: 'Tem certeza?' } %>
    <% end %>
    <%= f.submit 'Salvar', class: 'right sucess-btn' %>

  </div>
  </div>

<% end %>

app/views/categories/edit.html.erb
<div class="container">
  <div class="row category">
  <h2 class="s12 page-title">Editar Categorias</h2>

  <div class="notice-container">
    <p id="notice"><%= notice %></p>
  </div>
  <%= render 'form', category: @category %>

  </div>
</div>

app/views/categories/index.html.erb
<div class="container">
  <div class="row category">
  <h1 class="s12 page-title">Categorias</h1>

  <div class="notice-container">
    <p id="notice"><%= notice %></p>
  </div>

  <div class="s12 card card-large">
    <table id="table-user">
    <thead>
      <tr>
      <th>Nome</th>
      <th colspan="2"></th>
      </tr>
    </thead>
    <tbody>
      <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td class="taction"><%= link_to 'Editar', edit_category_path(category), class: 'btn-action primary-btn' %></td>
        <td class="taction"><%= link_to 'Excluir', category, class: 'btn-action danger-btn', method: :delete, data: { confirm: 'Tem certeza?' } %></td>
      </tr>
      <% end %>
    </tbody>

    </table>
    <div class="card-action right-align">
    <%= link_to 'Nova Categoria', new_category_path, class: 'primary-btn' %>
    </div>

  </div>
  </div>
</div>

app/views/categories/new.html.erb
<div class="container">
  <div class="row category">
  <h2 class="s12 page-title">Novo Categoria</h2>

  <div class="notice-container">
    <p id="notice"><%= notice %></p>
  </div>
  <%= render 'form', category: @category %>

  </div>
</div>