config/routes.rb
Rails.application.routes.draw do

  resources :recipes
  devise_for :users
  resources :categories

  resources :ingredients
  resources :users

  get 'search_by_categories' => 'home#search_by_categories', as: :search_by_categories
  get 'search_by_users' => 'home#search_by_users', as: :search_by_users

  root :to => "home#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <title>Leaf</title>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.ico' %>


  <%= stylesheet_link_tag  'application', media: 'all' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header>
    <ul id="nav-user" class="dropdown-content">
    <% if user_signed_in? %>
      <li><%= link_to 'Perfil', current_user %></li>
      <li><%= link_to 'Ingredientes', ingredients_path %></li>
      <li><%= link_to 'Categorias', categories_path %></li>
      <li><%= link_to 'Receitas', recipes_path %></li>
      <li class="nav-logout"><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
    <% else %>
      <li><%= link_to('Login', new_user_session_path)  %></li>
    <% end %>
    </ul>
    <nav class="nav-primary">
    <div class="nav-wrapper container" >
      <%= link_to '', root_path, class: 'brand-logo' %>
      <ul id="nav-mobile" class="right navbar-links">
        <li>
          <a class="dropdown-button link-dropdown" href="#!" data-activates="nav-user"><i class="ic-user"></i></a>
        </li>
      </ul>
    </div>
    </nav>
    <nav class="nav-secondary">
    <div class="nav-wrapper container">
      <ul class="left navbar-links">
        <li><%= link_to 'Home', root_path %></li>
        <li><%= link_to 'Categorias', search_by_categories_path %></li>
        <li><%= link_to 'Cadernos', search_by_users_path %></li>
      </ul>
    </div>
    </nav>
  </header>
  <main>
    <%= yield %>
  </main>
  </body>
</html>